-- Generated by experiments/export_lean_witness.py; regenerate rather than edit.
-- Config: configs/kovacs_hump_default.json
-- Config sha256: 46797c9aa07ba325e7952a5e0b55d1e6fc4bdddb515b96d38867f31110b5d8f7
-- Signature sha256: 4fdca727f7e7b87f8cfd89464b6cf699e04ca2931797a246eaacdb7aed0b173a
-- Scope: current mean energy and the declared 5-step energy probe.
-- Exact kernel evolution/tuning occurs in Python; Lean checks the exported rational
-- lookup separation and the corrected-core witness, strictness, and nonfactorization.
import GlassWitness.NumericCore

set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

namespace GlassWitness.NumericN10

def currentValue : Rat := (20 : Rat) / 7
def futureMu : Rat := (13643199600436809128613099751429307635947004495942869505416775988516581011811479975552281818467039174438570755608437457912610915268361897638703760482028070164407932467166932095241695887666265937 : Rat) / 4461939765513234360524882911829997870871840499299445558695359708950291920937467562985037664397759197806117518640785959502036479752067268452823868480780000000000000000000000000000000000000000000
def futureEq : Rat := (20 : Rat) / 7

def futureReadout (h : Fin 2) : Rat := if h.val = 0 then futureMu else futureEq

theorem future_split : futureReadout 0 ≠ futureReadout 1 := by decide +kernel

theorem strict_refinement :
    DeclaredMemory.StrictRefinement
      (Numeric.core currentValue futureReadout) GlassInterface.mid :=
  Numeric.strict_refinement currentValue futureReadout future_split

theorem nonfactorization :
    ¬ ∃ f : Rat → Rat, ∀ h : Fin 2, f currentValue = futureReadout h :=
  Numeric.nonfactorization currentValue futureReadout future_split

theorem current_panel_not_futureSufficient :
    ¬ DeclaredMemory.FutureSufficient (Numeric.core currentValue futureReadout)
      (i := GlassInterface.mid)
      (fun _ : Fin 2 => currentValue) :=
  Numeric.current_panel_not_futureSufficient currentValue futureReadout future_split

end GlassWitness.NumericN10
