-- Generated by experiments/export_lean_witness.py; regenerate rather than edit.
-- Config: configs/gt6_shell_witness_n8.json
-- Config sha256: 044aea07f53aaf18ef7ae3da5cc871f3a2f7ed6d14671a2da28c8a82ebef9558
-- Signature sha256: 33b5a318ef1c39776df2858c27d60d15120ac5f995f8790431f0a9879a61dc54
-- Scope: current mean energy and the declared 5-step energy probe.
-- Exact kernel evolution/tuning occurs in Python; Lean checks the exported rational
-- lookup separation and the corrected-core witness, strictness, and nonfactorization.
import GlassWitness.NumericCore

set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

namespace GlassWitness.NumericN8

def currentValue : Rat := (16 : Rat) / 7
def futureMu : Rat := (361147670370665593571880538502067425816571489853194101781543343404620006748101732350416207151877218270351 : Rat) / 144893259948738028897839552173351293160994488038652517427849091744666039051639482954152718569005280919552
def futureEq : Rat := (16 : Rat) / 7

def futureReadout (h : Fin 2) : Rat := if h.val = 0 then futureMu else futureEq

theorem future_split : futureReadout 0 ≠ futureReadout 1 := by decide +kernel

theorem strict_refinement :
    DeclaredMemory.StrictRefinement
      (Numeric.core currentValue futureReadout) GlassInterface.mid :=
  Numeric.strict_refinement currentValue futureReadout future_split

theorem nonfactorization :
    ¬ ∃ f : Rat → Rat, ∀ h : Fin 2, f currentValue = futureReadout h :=
  Numeric.nonfactorization currentValue futureReadout future_split

theorem current_panel_not_futureSufficient :
    ¬ DeclaredMemory.FutureSufficient (Numeric.core currentValue futureReadout)
      (i := GlassInterface.mid)
      (fun _ : Fin 2 => currentValue) :=
  Numeric.current_panel_not_futureSufficient currentValue futureReadout future_split

end GlassWitness.NumericN8
