"""Kovacs loop package and loop-score certificate helpers.

Loop images in this module are generated by the same row-wise East kernel that
is declared as the continuation. A hard-coded constant map is not valid loop
evidence.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from fractions import Fraction

from sixbirds_glass.models.east import build_east_kernel, east_energy
from sixbirds_glass.models.kernels import Kernel
from sixbirds_glass.pipeline.kovacs_witness import (
    DEFAULT_PROBE_STEPS,
    KovacsMomentWitness,
    build_kovacs_moment_history,
    solve_randomized_stop_theta,
)
from sixbirds_glass.pipeline.loops import loop_action_score
from sixbirds_glass.pipeline.package import (
    Continuation,
    Event,
    History,
    RouteTransportPackage,
    push_history,
)
from sixbirds_glass.pipeline.quotients import predictive_quotient
from sixbirds_glass.protocols.evolution import Distribution, dirac, expectation, hold, push

DEFAULT_LOOP_HOLD_STEPS = 1
DEFAULT_RETURN_EPSILON = Fraction(1, 10)
DEFAULT_MAX_RETURN_STEPS = 32
DEFAULT_CLOSURE_ROUND_CAP = 6
LoopImageFn = Callable[[Distribution], Distribution]


@dataclass(frozen=True)
class KovacsLoopCertificate:
    """Computed data for the finite Kovacs loop package."""

    package: RouteTransportPackage
    loop_image: Distribution
    theta_return: Fraction
    hold_steps: int
    return_steps: int
    closure_rounds: int
    closure_history_count: int
    closure_closed: bool
    loop_score_current: Fraction | None
    loop_score_predictive: Fraction | None
    loop_score_error: str | None


@dataclass(frozen=True)
class LoopClosureResult:
    """Declared mid-history closure attempt under one real loop application."""

    histories: tuple[History, ...]
    rounds: int
    closed: bool


def build_kovacs_loop_package(
    N: int,
    epsilon_mid: Fraction,
    mu_k: Distribution,
    pi_eq: Distribution,
    *,
    hold_steps: int = DEFAULT_LOOP_HOLD_STEPS,
    epsilon_return: Fraction = DEFAULT_RETURN_EPSILON,
) -> tuple[RouteTransportPackage, Distribution, Fraction, int, LoopClosureResult]:
    """Declare a finite endo-loop package from a real tuned East loop kernel."""

    loop_kernel, loop_image, theta_return, return_steps, loop_image_fn = tune_kovacs_loop_kernel(
        N, epsilon_mid, epsilon_return, mu_k, hold_steps=hold_steps
    )
    state_count = 1 << N
    closure = close_histories_under_loop(
        (History("mu_K", "mid", mu_k), History("pi_eq", "mid", pi_eq)),
        loop_image_fn,
        round_cap=DEFAULT_CLOSURE_ROUND_CAP,
    )
    return (
        RouteTransportPackage(
            interfaces=("mid", "probe"),
            projections={"mid": lambda state: state, "probe": lambda state: state},
            histories={"mid": closure.histories, "probe": ()},
            continuations={
                ("mid", "mid"): (Continuation("loop_kovacs", "mid", "mid", loop_kernel),),
                ("mid", "probe"): (
                    Continuation(
                        "probe_hold",
                        "mid",
                        "probe",
                        _powered_kernel(N, epsilon_mid, DEFAULT_PROBE_STEPS),
                    ),
                ),
            },
            events={"mid": (_energy_event(N),), "probe": (_energy_event(N),)},
            identity={
                "mid": Continuation("id_mid", "mid", "mid", _identity_kernel(N, state_count)),
                "probe": Continuation(
                    "id_probe", "probe", "probe", _identity_kernel(N, state_count)
                ),
            },
            future_catalog={"mid": (("probe_hold", "w_E"),), "probe": ()},
        ),
        loop_image,
        theta_return,
        return_steps,
        closure,
    )


def build_kovacs_loop_certificate(
    witness: KovacsMomentWitness,
    *,
    hold_steps: int = DEFAULT_LOOP_HOLD_STEPS,
    epsilon_return: Fraction = DEFAULT_RETURN_EPSILON,
) -> KovacsLoopCertificate:
    """Build the real loop package and try to compute exact loop scores.

    The real loop returns ``mu_K``'s current panel exactly. P1-02 loop scores
    additionally require every quotient-representative image to be predeclared;
    if the real loop fails that finite-closure requirement, this function
    records the error instead of substituting a synthetic map.
    """

    package, loop_image, theta_return, return_steps, closure = build_kovacs_loop_package(
        witness.N,
        witness.epsilon_mid,
        witness.mu_k,
        witness.pi_eq,
        hold_steps=hold_steps,
        epsilon_return=epsilon_return,
    )
    current_score: Fraction | None
    predictive_score: Fraction | None
    score_error: str | None
    if not closure.closed:
        current_score = None
        predictive_score = None
        score_error = (
            "real Kovacs loop history closure did not stabilize within "
            f"{closure.rounds} rounds; declared {len(closure.histories)} histories"
        )
    else:
        try:
            current_score, predictive_score = kovacs_loop_scores(package)
            score_error = None
        except ValueError as exc:
            current_score = None
            predictive_score = None
            score_error = str(exc)
    return KovacsLoopCertificate(
        package=package,
        loop_image=loop_image,
        theta_return=theta_return,
        hold_steps=hold_steps,
        return_steps=return_steps,
        closure_rounds=closure.rounds,
        closure_history_count=len(closure.histories),
        closure_closed=closure.closed,
        loop_score_current=current_score,
        loop_score_predictive=predictive_score,
        loop_score_error=score_error,
    )


def close_histories_under_loop(
    seed_histories: tuple[History, ...],
    loop_image_fn: LoopImageFn,
    *,
    round_cap: int = DEFAULT_CLOSURE_ROUND_CAP,
) -> LoopClosureResult:
    """Declare loop images until exact one-step closure or ``round_cap``."""

    histories = list(seed_histories)
    frontier = list(seed_histories)
    next_index = 0
    for round_number in range(1, round_cap + 1):
        added: list[History] = []
        known = [history.distribution for history in histories]
        for history in frontier:
            image = loop_image_fn(history.distribution)
            if _distribution_declared(image, known) or _distribution_declared(
                image, [new_history.distribution for new_history in added]
            ):
                continue
            added.append(History(f"loop_image_{next_index}", history.interface, image))
            next_index += 1
        if not added:
            return LoopClosureResult(tuple(histories), round_number, True)
        histories.extend(added)
        frontier = added
    return LoopClosureResult(tuple(histories), round_cap, False)


def tune_kovacs_loop_kernel(
    N: int,
    epsilon_mid: Fraction,
    epsilon_return: Fraction,
    mu_k: Distribution,
    *,
    hold_steps: int,
) -> tuple[Kernel, Distribution, Fraction, int, LoopImageFn]:
    """Build a real randomized-stop East loop returning ``mu_k``'s energy.

    The kernel is ``K_mid^hold_steps`` followed by
    ``theta*K_return^r + (1-theta)*K_return^(r+1)`` row by row. The tuning
    endpoints are actual evolved distributions of ``mu_K``.
    """

    target = _energy_expectation(mu_k, N)
    mid_kernel = build_east_kernel(N, epsilon_mid)
    return_kernel = build_east_kernel(N, epsilon_return)
    left = hold(mu_k, mid_kernel, hold_steps)
    left_value = _energy_expectation(left, N)
    for return_steps in range(DEFAULT_MAX_RETURN_STEPS + 1):
        right = push(left, return_kernel)
        right_value = _energy_expectation(right, N)
        if left_value != right_value and min(left_value, right_value) <= target <= max(
            left_value, right_value
        ):
            theta = solve_randomized_stop_theta(left_value, right_value, target)
            image = build_kovacs_moment_history(left, right, theta)
            if _energy_expectation(image, N) != target:
                raise ValueError("real Kovacs loop image did not return the current panel")
            kernel = _randomized_stop_composite_kernel(
                N,
                epsilon_mid,
                hold_steps,
                epsilon_return,
                return_steps,
                theta,
            )
            loop_image_fn = _loop_image_function(
                mid_kernel, return_kernel, hold_steps, return_steps, theta
            )
            loop = Continuation("loop_kovacs", "mid", "mid", kernel)
            if push_history(History("mu_K", "mid", mu_k), loop) != image:
                raise ValueError("declared loop kernel does not reproduce the tuned loop image")
            if loop_image_fn(mu_k) != image:
                raise ValueError("leg-by-leg loop image function disagrees with declared kernel")
            return (kernel, image, theta, return_steps, loop_image_fn)
        left = right
        left_value = right_value
    raise ValueError(
        "real Kovacs loop did not bracket the return target within "
        f"{DEFAULT_MAX_RETURN_STEPS} return steps"
    )


def tune_kovacs_loop_image(
    N: int,
    epsilon_mid: Fraction,
    epsilon_return: Fraction,
    mu_k: Distribution,
    *,
    hold_steps: int,
) -> tuple[Distribution, Fraction, int]:
    """Return the real tuned loop image, theta, and return depth."""

    _kernel, image, theta, return_steps, _loop_image_fn = tune_kovacs_loop_kernel(
        N, epsilon_mid, epsilon_return, mu_k, hold_steps=hold_steps
    )
    return (image, theta, return_steps)


def kovacs_loop_scores(package: RouteTransportPackage) -> tuple[Fraction, Fraction]:
    """Return ``(loop_Q, loop_M)`` for the declared ``loop_kovacs`` continuation."""

    loop = package.continuation_by_label("mid", "loop_kovacs")
    return (
        loop_action_score(package, "mid", (loop,), quotient_kind="current"),
        loop_action_score(package, "mid", (loop,), quotient_kind="predictive"),
    )


def build_constant_temperature_control_package(
    N: int,
    epsilon_mid: Fraction,
    pi_eq: Distribution,
    *,
    hold_steps: int = DEFAULT_LOOP_HOLD_STEPS,
) -> RouteTransportPackage:
    """Return a singleton equilibrium loop control with scores ``(0, 0)``."""

    state_count = 1 << N
    return RouteTransportPackage(
        interfaces=("mid", "probe"),
        projections={"mid": lambda state: state, "probe": lambda state: state},
        histories={"mid": (History("pi_eq", "mid", pi_eq),), "probe": ()},
        continuations={
            ("mid", "mid"): (
                Continuation(
                    "loop_const_temp", "mid", "mid", _powered_kernel(N, epsilon_mid, hold_steps)
                ),
            ),
            ("mid", "probe"): (
                Continuation(
                    "probe_hold",
                    "mid",
                    "probe",
                    _powered_kernel(N, epsilon_mid, DEFAULT_PROBE_STEPS),
                ),
            ),
        },
        events={"mid": (_energy_event(N),), "probe": (_energy_event(N),)},
        identity={
            "mid": Continuation("id_mid", "mid", "mid", _identity_kernel(N, state_count)),
            "probe": Continuation("id_probe", "probe", "probe", _identity_kernel(N, state_count)),
        },
        future_catalog={"mid": (("probe_hold", "w_E"),), "probe": ()},
    )


def predictive_class_count(package: RouteTransportPackage) -> int:
    """Return the predictive quotient size for artifact action summaries."""

    return len(predictive_quotient(package, "mid"))


def _energy_event(N: int) -> Event:
    return Event("w_E", {state: Fraction(east_energy(state, N)) for state in range(1 << N)})


def _energy_expectation(distribution: Distribution, N: int) -> Fraction:
    return expectation(distribution, lambda state: east_energy(state, N))


def _distribution_declared(distribution: Distribution, declared: list[Distribution]) -> bool:
    return any(distribution == known for known in declared)


def _powered_kernel(N: int, epsilon: Fraction, steps: int) -> Kernel:
    base = build_east_kernel(N, epsilon)
    state_count = 1 << N
    return Kernel(
        N=N,
        state_count=state_count,
        rows={state: hold(dirac(state), base, steps) for state in range(state_count)},
    )


def _randomized_stop_composite_kernel(
    N: int,
    epsilon_mid: Fraction,
    hold_steps: int,
    epsilon_return: Fraction,
    return_steps: int,
    theta: Fraction,
) -> Kernel:
    if not Fraction(0) <= theta <= Fraction(1):
        raise ValueError(f"theta must lie in [0, 1]; got {theta}")
    mid_kernel = build_east_kernel(N, epsilon_mid)
    return_kernel = build_east_kernel(N, epsilon_return)
    state_count = 1 << N
    rows: dict[int, dict[int, Fraction]] = {}
    for state in range(state_count):
        after_mid = hold(dirac(state), mid_kernel, hold_steps)
        left = hold(after_mid, return_kernel, return_steps)
        right = push(left, return_kernel)
        rows[state] = build_kovacs_moment_history(left, right, theta)
    return Kernel(N=N, state_count=state_count, rows=rows)


def _loop_image_function(
    mid_kernel: Kernel,
    return_kernel: Kernel,
    hold_steps: int,
    return_steps: int,
    theta: Fraction,
) -> LoopImageFn:
    def apply(distribution: Distribution) -> Distribution:
        after_mid = hold(distribution, mid_kernel, hold_steps)
        left = hold(after_mid, return_kernel, return_steps)
        right = push(left, return_kernel)
        return build_kovacs_moment_history(left, right, theta)

    return apply


def _identity_kernel(N: int, state_count: int) -> Kernel:
    return Kernel(
        N=N,
        state_count=state_count,
        rows={state: {state: Fraction(1)} for state in range(state_count)},
    )
